<?php

namespace Database\Seeders;

use Carbon\Carbon;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class IndividualInvesteeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            $ind_investee1=[
                'name' => 'Sushil Shrestha',
                'email' => 'sushil@yopmail.com',
                'phone' => '9876543210',
                'sex' => 'Male',
                'dob' => '1990-05-15',
                'image' => 'new-dashboard/img/profile_picture/sushil.jpg',
                'father_name' => 'Dayaram Shrestha',
                'grand_father_name' => 'Ramprasad Shrestha',
                'province' => 'Province 1',
                'district' => 'JHAPA',
                'municipality' => 'Birtamod Municipality',
                'locality' => 'Thamel',
                'ward' => '5',
                'temporary_province' => 'BAGMATI',
                'temporary_district' => 'LALITPUR',
                'temporary_municipality' => 'Lalitpur Metropolitian City',
                'temporary_locality' => 'Jhamsikhel',
                'temporary_ward' => '10',
                'citizenship_number' => '1234567890',
                'citizenship_issue_date' => '2010-01-01',
                'citizenship_issue_district' => 'JHAPA',
                'citizenship_front_document' => 'new-dashboard/img/citizenship_front.png',
                'citizenship_back_document' => 'new-dashboard/img/citizenship_back.jpg',
                'account_type' => 'individual',
                'kyc_status' => 'verified',
                'kyc_remarks' => null,
                'description' => 'Passionate investor interested in technology startups.',
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
                'created_at'=>Carbon::now()->subDays(rand(1, 30)),
            ],
            $ind_investee2=[
                'name' => 'Sarita Maharjan',
                'email' => 'sarita_mhz@yopmail.com',
                'phone' => '9843215678',
                'sex' => 'Female',
                'dob' => '1988-08-25',
                'image' => 'new-dashboard/img/profile_picture/sarita_mhz.jpg',
                'father_name' => 'Bishnu Maharjan',
                'grand_father_name' => 'Hari Maharjan',
                'province' => 'BAGMATI',
                'district' => 'BHAKTAPUR',
                'municipality' => 'Suryabinayak Municipality',
                'locality' => 'Dattatreya Square',
                'ward' => '2',
                'temporary_province' => 'BAGMATI',
                'temporary_district' => 'BHAKTAPUR',
                'temporary_municipality' => 'Suryabinayak Municipality',
                'temporary_locality' => 'Dattatreya Square',
                'temporary_ward' => '2',
                'citizenship_number' => '9876543210',
                'citizenship_issue_date' => '2005-12-10',
                'citizenship_issue_district' => 'BHAKTAPUR',
                'citizenship_front_document' => 'new-dashboard/img/citizenship_front.png',
                'citizenship_back_document' => 'new-dashboard/img/citizenship_back.jpg',
                'account_type' => 'individual',
                'kyc_status' => 'processing',
                'kyc_remarks' => null,
                'description' => 'Passionate about sustainable investments.',
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
                'created_at'=>Carbon::now()->subDays(rand(1, 30)),
            ],
            $ind_investee3=[
                'name' => 'Rajesh Shahi',
                'email' => 'rajesh_shahi@yopmail.com',
                'phone' => '9812345678',
                'sex' => 'Male',
                'dob' => '1992-03-18',
                'image' => 'new-dashboard/img/profile_picture/rajesh_shahi.jpg',
                'father_name' => 'Gopal Shahi',
                'grand_father_name' => 'Krishna Shahi',
                'province' => 'GANDAKI',
                'district' => 'KASKI',
                'municipality' => 'Pokhara Metropolitian City',
                'locality' => 'Lakeside',
                'ward' => '6',
                'temporary_province' => 'GANDAKI',
                'temporary_district' => 'KASKI',
                'temporary_municipality' => 'Pokhara Metropolitian City',
                'temporary_locality' => 'Lakeside',
                'temporary_ward' => '6',
                'citizenship_number' => '8765432109',
                'citizenship_issue_date' => '2008-05-20',
                'citizenship_issue_district' => 'KASKI',
                'citizenship_front_document' => 'new-dashboard/img/citizenship_front.png',
                'citizenship_back_document' => 'new-dashboard/img/citizenship_back.jpg',
                'account_type' => 'individual',
                'kyc_status' => 'verified',
                'kyc_remarks' => null,
                'description' => 'Tech enthusiast and early-stage investor.',
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
                'created_at'=>Carbon::now()->subDays(rand(1, 30)),
            ],
            $ind_investee4=[
                'name' => 'Anita Thapa',
                'email' => 'anita@yopmail.com',
                'phone' => '9856781234',
                'sex' => 'Female',
                'dob' => '1995-02-18',
                'image' => 'new-dashboard/img/profile_picture/anita.jpg',
                'father_name' => 'Ganesh Thapa',
                'grand_father_name' => 'Narayan Thapa',
                'province' => 'BAGMATI',
                'district' => 'KATHMANDU',
                'municipality' => 'Kathmandu Metropolitian City',
                'locality' => 'Boudhanath',
                'ward' => '3',
                'temporary_province' => 'BAGMATI',
                'temporary_district' => 'KATHMANDU',
                'temporary_municipality' => 'Kathmandu Metropolitian City',
                'temporary_locality' => 'Boudhanath',
                'temporary_ward' => '3',
                'citizenship_number' => '8765432101',
                'citizenship_issue_date' => '2010-07-15',
                'citizenship_issue_district' => 'KATHMANDU',
                'citizenship_front_document' => 'new-dashboard/img/citizenship_front.png',
                'citizenship_back_document' => 'new-dashboard/img/citizenship_back.jpg',
                'account_type' => 'individual',
                'kyc_status' => 'verified',
                'kyc_remarks' => null,
                'description' => 'Passionate about social impact investing.',
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
                'created_at'=>Carbon::now()->subDays(rand(1, 30)),
            ],
            $ind_investee5=[
                'name' => 'Rajendra Tamang',
                'email' => 'rajendra@yopmail.com',
                'phone' => '9812345678',
                'sex' => 'Male',
                'dob' => '1990-11-22',
                'image' => 'new-dashboard/img/profile_picture/rajendra.jpg',
                'father_name' => 'Bikram Tamang',
                'grand_father_name' => 'Keshav Tamang',
                'province' => 'GANDAKI',
                'district' => 'KASKI',
                'municipality' => 'Pokhara Metropolitian City',
                'locality' => 'Lakeside',
                'ward' => '5',
                'temporary_province' => 'GANDAKI',
                'temporary_district' => 'KASKI',
                'temporary_municipality' => 'Pokhara Metropolitian City',
                'temporary_locality' => 'Lakeside',
                'temporary_ward' => '5',
                'citizenship_number' => '7654321098',
                'citizenship_issue_date' => '2010-06-30',
                'citizenship_issue_district' => 'KASKI',
                'citizenship_front_document' => 'new-dashboard/img/citizenship_front.png',
                'citizenship_back_document' => 'new-dashboard/img/citizenship_back.jpg',
                'account_type' => 'individual',
                'kyc_status' => 'rejected',
                'kyc_remarks' => 'Citizenship Picture not Clear',
                'description' => 'Investor with a keen interest in technology startups.',
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
                'created_at'=>Carbon::now()->subDays(rand(1, 30)),
            ],
            $ind_investee6=[
                'name' => 'Neha Gurung',
                'email' => 'neha@yopmail.com',
                'phone' => '9845671230',
                'sex' => 'Female',
                'dob' => '1993-04-12',
                'image' => 'new-dashboard/img/profile_picture/neha.jpg',
                'father_name' => 'Amit Gurung',
                'grand_father_name' => 'Gopal Gurung',
                'province' => 'GANDAKI',
                'district' => 'KASKI',
                'municipality' => 'Pokhara Metropolitian City',
                'locality' => 'Sarangkot',
                'ward' => '7',
                'temporary_province' => 'GANDAKI',
                'temporary_district' => 'KASKI',
                'temporary_municipality' => 'Pokhara Metropolitian City',
                'temporary_locality' => 'Sarangkot',
                'temporary_ward' => '7',
                'citizenship_number' => '8765432102',
                'citizenship_issue_date' => '2011-05-20',
                'citizenship_issue_district' => 'KASKI',
                'citizenship_front_document' => 'new-dashboard/img/citizenship_front.png',
                'citizenship_back_document' => 'new-dashboard/img/citizenship_back.jpg',
                'account_type' => 'individual',
                'kyc_status' => 'verified',
                'kyc_remarks' => null,
                'description' => 'Nature lover and enthusiast for eco-friendly initiatives.',
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
                'created_at'=>Carbon::now()->subDays(rand(1, 30)),
            ],
            $ind_investee7=    [
                'name' => 'Bimala Khadka',
                'email' => 'bimala@yopmail.com',
                'phone' => '9812345678',
                'sex' => 'Female',
                'dob' => '1994-09-08',
                'image' => 'new-dashboard/img/profile_picture/bimala.jpg',
                'father_name' => 'Dinesh Khadka',
                'grand_father_name' => 'Nabin Khadka',
                'province' => 'LUMBINI',
                'district' => 'PALPA',
                'municipality' => 'Tansen Municipality',
                'locality' => 'Milanchowk',
                'ward' => '2',
                'temporary_province' => 'LUMBINI',
                'temporary_district' => 'PALPA',
                'temporary_municipality' => 'Tansen Municipality',
                'temporary_locality' => 'Milanchowk',
                'temporary_ward' => '2',
                'citizenship_number' => '7654321097',
                'citizenship_issue_date' => '2010-04-25',
                'citizenship_issue_district' => 'PALPA',
                'citizenship_front_document' => 'new-dashboard/img/citizenship_front.png',
                'citizenship_back_document' => 'new-dashboard/img/citizenship_back.jpg',
                'account_type' => 'individual',
                'kyc_status' => 'verified',
                'kyc_remarks' => null,
                'description' => 'Health and wellness advocate, interested in healthcare startups.',
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
                'created_at'=>Carbon::now()->subDays(rand(1, 30)),
            ],
            $ind_investee8=[
                'name' => 'Dilip Sharma',
                'email' => 'dilip@yopmail.com',
                'phone' => '9845671234',
                'sex' => 'Male',
                'dob' => '1985-07-12',
                'image' => 'new-dashboard/img/profile_picture/dilip.jpg',
                'father_name' => 'Hari Sharma',
                'grand_father_name' => 'Ramesh Sharma',
                'province' => 'MADHESH',
                'district' => 'DHANUSA',
                'municipality' => 'Janakpurdham Sub-Metropolitian City',
                'locality' => 'Dhanushadham',
                'ward' => '7',
                'temporary_province' => 'MADHESH',
                'temporary_district' => 'DHANUSA',
                'temporary_municipality' => 'Janakpurdham Sub-Metropolitian City',
                'temporary_locality' => 'Dhanushadham',
                'temporary_ward' => '7',
                'citizenship_number' => '5432109876',
                'citizenship_issue_date' => '2002-03-05',
                'citizenship_issue_district' => 'DHANUSA',
                'citizenship_front_document' => 'new-dashboard/img/citizenship_front.png',
                'citizenship_back_document' => 'new-dashboard/img/citizenship_back.jpg',
                'account_type' => 'individual',
                'kyc_status' => 'verified',
                'kyc_remarks' => null,
                'description' => 'Experienced investor in the agriculture sector.',
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
                'created_at'=>Carbon::now()->subDays(rand(1, 30)),
            ],
            $ind_investee9=[
                'name' => 'Nisha Rai',
                'email' => 'nisha@yopmail.com',
                'phone' => '9812345678',
                'sex' => 'Female',
                'dob' => '1993-05-28',
                'image' => 'new-dashboard/img/profile_picture/nisha.jpg',
                'father_name' => 'Suresh Rai',
                'grand_father_name' => 'Dhan Bahadur Rai',
                'province' => 'Province 1',
                'district' => 'ILAM',
                'municipality' => 'Suryodaya Municipality',
                'locality' => 'Birat Chowk',
                'ward' => '1',
                'temporary_province' => 'Province 1',
                'temporary_district' => 'ILAM',
                'temporary_municipality' => 'Suryodaya Municipality',
                'temporary_locality' => 'Birat Chowk',
                'temporary_ward' => '1',
                'citizenship_number' => '7654321098',
                'citizenship_issue_date' => '2011-12-18',
                'citizenship_issue_district' => 'ILAM',
                'citizenship_front_document' => 'new-dashboard/img/citizenship_front.png',
                'citizenship_back_document' => 'new-dashboard/img/citizenship_back.jpg',
                'account_type' => 'individual',
                'kyc_status' => 'processing',
                'kyc_remarks' => null,
                'description' => 'Passionate about empowering women-led businesses.',
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
                'created_at'=>Carbon::now()->subDays(rand(1, 30)),
            ],
            $ind_investee10=[
                'name' => 'Nabin Basnet',
                'email' => 'nabin_basnet@yopmail.com',
                'phone' => '9845671234',
                'sex' => 'Male',
                'dob' => '1987-03-15',
                'image' => 'new-dashboard/img/profile_picture/nabin_basnet.jpg',
                'father_name' => 'Dinesh Basnet',
                'grand_father_name' => 'Ram Basnet',
                'province' => 'MADHESH',
                'district' => 'SARLAHI',
                'municipality' => 'Lalbandi Municipality',
                'locality' => 'Maisthan',
                'ward' => '4',
                'temporary_province' => 'MADHESH',
                'temporary_district' => 'SARLAHI',
                'temporary_municipality' => 'Lalbandi Municipality',
                'temporary_locality' => 'Maisthan',
                'temporary_ward' => '4',
                'citizenship_number' => '5432109876',
                'citizenship_issue_date' => '2004-10-10',
                'citizenship_issue_district' => 'SARLAHI',
                'citizenship_front_document' => 'new-dashboard/img/citizenship_front.png',
                'citizenship_back_document' => 'new-dashboard/img/citizenship_back.jpg',
                'account_type' => 'individual',
                'kyc_status' => 'verified',
                'kyc_remarks' => null,
                'description' => 'Entrepreneur with interests in hospitality and tourism.',
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
                'created_at'=>Carbon::now()->subDays(rand(1, 30)),
            ],
        ]);
        $ind_investee1 = User::find(12);
        $ind_investee2 = User::find(13);
        $ind_investee3 = User::find(14);
        $ind_investee4 = User::find(15);
        $ind_investee5 = User::find(16);
        $ind_investee6 = User::find(17);
        $ind_investee7 = User::find(18);
        $ind_investee8 = User::find(19);
        $ind_investee9 = User::find(20);
        $ind_investee10 = User::find(21);

        //Assign Role
        $ind_investee1->assignRole('investee');
        $ind_investee2->assignRole('investee');
        $ind_investee3->assignRole('investee');
        $ind_investee4->assignRole('investee');
        $ind_investee5->assignRole('investee');
        $ind_investee6->assignRole('investee');
        $ind_investee7->assignRole('investee');
        $ind_investee8->assignRole('investee');
        $ind_investee9->assignRole('investee');
        $ind_investee10->assignRole('investee');

        //Sync Interests
        $ind_investee1->sectors()->sync([4, 7, 10, 12]);
        $ind_investee2->sectors()->sync([1, 5, 8, 11]);
        $ind_investee3->sectors()->sync([2, 6, 9, 13]);
        $ind_investee4->sectors()->sync([3, 7, 10, 12]);
        $ind_investee5->sectors()->sync([1, 4, 8, 11]);
        $ind_investee6->sectors()->sync([2, 6, 9, 13]);
        $ind_investee7->sectors()->sync([4, 7, 10, 12]);
        $ind_investee8->sectors()->sync([1, 5, 8, 11]);
        $ind_investee9->sectors()->sync([2, 6, 9, 13]);
        $ind_investee10->sectors()->sync([3, 7, 10, 12]);


    }
}
